config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match 'vote', to: 'votes#vote', via: :post
  match 'unvote', to: 'votes#unvote', via: :delete

  resources :events
  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    validates :name, uniqueness: true
    has_one :place
end

app/models/event.rb
class Event < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :place_id, presence: true

    belongs_to :place
    has_many :votes, dependent: :destroy
    has_many :users, through: :votes
    has_one_attached :picture1
    has_one_attached :picture2
    has_one_attached :picture3
end

app/models/place.rb
class Place < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :events
    belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

# after_create :send_welcome_mail

  has_many :votes, dependent: :destroy
  has_many :events, through: :votes

  def send_welcome_mail
	#  UserMailer.welcome_email(self).deliver_now!
  end

    # creates a new vote row with event_id and user_id
  def vote!(event)
    self.votes.create!(event_id: event.id)
  end

  # destroys a vote with matching event_id and user_id
  def unvote!(event)
    vote = self.votes.find_by_event_id(event.id)
    vote.destroy!
  end

  # returns true of false if a event is voted by user
  def vote?(event)
    self.votes.find_by_event_id(event.id)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :event, counter_cache: true

    validates :user_id, uniqueness: { scope: :event_id }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
@cities = City.all 
protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

		devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
	end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.friendly.find(params[:id])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.where(:active => true)
  end

  def show
    @event = Event.friendly.find(params[:id])
    @city_of_event = City.find(Place.find(Event.friendly.find(params[:id]).place_id).id)
    @place_of_event = Place.find(Event.friendly.find(params[:id]).place_id)
  end

  def events_params
    params.require(:events).permit(:picture1)
    params.require(:events).permit(:picture2)
    params.require(:events).permit(:picture3)
  end

  def create

  	@event_new = Event.new(
      name: params[:new][:name], 
      description: params[:new][:description], 
      place_id: Place.find_by(city_id: params[:new][:city_id]).id, 
      picture1: params[:new][:picture1], 
      picture2: params[:new][:picture2], 
      picture3: params[:new][:picture3]
    )
    
    if @event_new.save && params[:new][:picture1].present?
      flash[:notice] = "Projet créé avec succès !"
      redirect_to root_path
    else 
      flash[:notice] = "Merci de réessayer"
  		redirect_to new_event_path
  	end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @cities = City.order(Arel.sql("RANDOM()")).limit(3)
    @places = Place.all
    @events = Event.all
  end

end

app/controllers/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

    respond_to :js

    def vote
      @user = current_user
      @event = Event.find(params[:event_id])
      @user.vote!(@event)
    end
    
    def unvote
      @user = current_user
      @vote = @user.votes.find_by_event_id(params[:event_id])
      @event = Event.find(params[:event_id])
      @vote.destroy!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/cities/index.html.erb
<div>
    <div id="portfolio" class="clearfix fullwidth portfolio-nogutter portfolio-isotope portfolio-isotope-3">
        <% @cities.each do |city| %>
            <div class="portfolio-item"><!-- item -->
                <div class="item-box">
                    <%= link_to city_path(id: city) do %>
                        <figure>
                            <span class="item-hover">
                                <span class="overlay dark-5"></span>
                                <span class="inner">
                                    <span style="font-size: 50px"><span style="color: #1ABC9C"><%= city.name[0] %></span><span><%= city.name[1..-1] %><span style="color: #1ABC9C">.</span></span>
                                    </span>
                                    <!-- lightbox -->
                                    <a class="ico-rounded lightbox">
                                    </a>
                                </span>
                            </span>
                        <%= image_tag(city.image_url, size:"800", class:"img-fluid") %>
                    <% end %>
                    </figure>
                </div>
            </div><!-- /item -->
        <% end %>
    </div>
</div>

app/views/cities/show.html.erb
			<!-- 
				PAGE HEADER 
				
				CLASSES:
					.page-header-xs	= 20px margins
					.page-header-md	= 50px margins
					.page-header-lg	= 80px margins
					.page-header-xlg= 130px margins
					.dark		= dark page header
					.light		= light page header
			-->
			<section class="page-header page-header-md b-0 dark" 
				data-background="<%= image_path(@city.place.image_url) %>">

				<span class="overlay dark-6"><!-- dark overlay [1 to 9 opacity] --></span>
				<div class="container">

                    <div class="heading-title heading-border heading-color mt-0">
                        <p class="fs-15">Bienvenue sur la page de:<p>
                        <p class="fs-55"><strong style="color: #1ABC9C"><%= @city.name[0] %></strong><strong><%= @city.name[1..-1] %><span style="color: #1ABC9C">.</strong></span><p>
                        <p class="fs-20">Le lieu actuel de cette ville "<%= @city.place.name %>"<p>
                        <p class="fs-20">Vous retrouverez ici tous les évènements que la communauté a proposé pour le lieu de <%= @city.name %><p>
					</div>

                    <% if user_signed_in? %>
                    <p class="fs-15"> Adresse: <%= @city.place.address %><p>
                        
                            <div id="pin">        
                                <br><br>                        
                                <small>📍 Localisation<small>
                                <%= image_tag("pin.png", size: "100", class: "rounded mx-auto d-block") %>
                            </div>

                        <div id="map" style="margin: 0 auto"></div>

                    <% else %>
                    <p class="fs-20" style="text-align: center">Connectez-vous pour plus d'informations.<p>
                    <% end %>
				</div>
			</section>
			<!-- /PAGE HEADER -->


            <!-- -->


</div>

<div class="container">
<div class="row category-grid">
            <% @city.place.events.where(:active => true).reverse_order.each do |event| %>    

                        <div class="col-lg-3 col-md-3 col-sm-6 col-12">
                            <div class="card">
                            <%= link_to event_path(id: event) do %>
                            <% if event.picture1.attached? %> 
                                <%= image_tag(event.picture1, class: "card-img-top") %> 
                            <% else %>
                                <%= image_tag(event.image1, class: "card-img-top")%>
                            <% end %>     
                            <% end %>       
                                <div class="card-block">
                                    <p class="text-black fs-20 mb-6 block"> <b><%= event.name %></b></p>
                                    <p class="text-black fs-16 mb-8 block">à <%= event.place.city.name %></p>


                                    <div class="all"> <br>
                                        <div class="progress progress-xxs center" style="width: 100%; max-width: 100%; height: 0.5em; display: inline-block; text-align: center; position: inherit">
                                            <div class="progress-bar" style="width: <%= (((event.votes.count)*100)/User.count) %>%; max-width: 100%; height: 0.5em;background-color: #99D17B"></div>
                                        </div>
                                    </div>
                                
                                    <p class="text-black fs-16 mb-20 block" style="display: inline-block; text-align: center;"><%= event.votes.count %> votes ❤️</p>
                                    <p class="fs-15 mb-20"><%= event.description %></p>
                                    <%= link_to "VIEW PROJECT", event_path(id: event), class: "text-muted fs-15" %>
                                </div>
                            </div>
                        </div>
                        <% end %>
</div>
</div>




<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.googlejs_api %>&callback=initMap"></script>

    <script>
function initMap() {
// Localisation test pour paris
var paris = {lat: <%= @city.place.latitude %> , lng: <%= @city.place.longitude %> };
// la map est centrée sur paris
var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 15, center: paris});
// le marker est positionné sur paris
var marker = new google.maps.Marker({position: paris, map: map});
}
    </script>

app/views/events/index.html.erb
<div class="container">
<div class="row category-grid">

        <% @events.where(:active => true).order(:votes_count).reverse_order.each do |event| %>    

                        <div class="col-lg-3 col-md-3 col-sm-6 col-12">

                            <div class="card">
                            <%= link_to event_path(id: event) do %>
                            <% if event.picture1.attached? %> 
                                <%= image_tag(event.picture1, class: "card-img-top") %> 
                            <% else %>
                                <%= image_tag(event.image1, class: "card-img-top")%>
                            <% end %>        
                            <% end %>
                                <div class="card-block">
                                    <p class="text-black fs-20 mb-6 block"> <b><%= event.name %></b></p>
                                    <p class="text-black fs-16 mb-8 block">à <%= event.place.city.name %></p>


                                    <div class="all"> <br>
                                        <div class="progress progress-xxs center" style="width: 100%; max-width: 100%; height: 0.5em; display: inline-block; text-align: center; position: inherit">
                                            <div class="progress-bar" style="width: <%= (((event.votes.count)*100)/User.count) %>%; max-width: 100%; height: 0.5em;background-color: #99D17B"></div>
                                        </div>
                                    </div>
                                
                                    <p class="text-black fs-16 mb-20 block" style="display: inline-block; text-align: center;"><%= event.votes.count %> votes ❤️</p>
                                    <p class="fs-15 mb-20"><%= event.description %></p>
                                    <p style="text-align:center"><%= link_to "Voir le Projet", event_path(id: event), class: "text-muted fs-15" %></p>
                                </div>
                            </div>
                            </figure>
                        </div>
                        <% end %>
</div>
</div>

app/views/events/new.html.erb
<section>
  <div class="container"> 
    <div class="row">
      <div class="col-md-6">
          <h2 class="fs-30 text-center-xs">Proposer un projet.</h2>

          <p>La proposition de projet est est ouverte à toutes et à tous.</p>

          <ul class="list-unstyled login-features">
            <li>
              <i class="glyphicon glyphicon-picture"></i> <strong>Au moins une image</strong> au format .png ou .jpg est requise pour pouvoir avoir un projet éligible à la publication.
            </li>
            <li>
              <i class="glyphicon glyphicon-check"></i> <strong>Si votre projet est accepté</strong> par la modération, il sera publié sous 48h sur le site.
            </li>
            <li>
              <i class="glyphicon glyphicon-usd"></i> <strong>Une fois publié</strong> il sera soumis au vote de la communauté, et pourra recevoir des dons pour sa réalisation.
            </li>
            <li>
              <i class="glyphicon glyphicon-thumbs-up"></i> <strong>Dès 500 votes réunis</strong> votre projet sehra sélectionné pour bénéficier de l’accompagnement de Sehra pour sa mise en place et son développement.
            </li>
          </ul>

      </div>
      <div class="col-md-6">
        <div class="row">
      <div class="col-lg-11 col-md-9 col-sm-8 order-lg-1 order-md-2 order-sm-2 mb-30">
        <div class="box-light">
          <div class="box-inner">
              <div style="text-align:center;">
                  <% if user_signed_in? %>
                  <div class="section">
                  <%= form_for :new, url: events_path do |f| %>
                  <%= f.text_field :name, class:"form-control form-control-lg", placeholder:"Nom du Projet" %>              
                  <%= f.text_area :description, class:"form-control form-control-lg", style:"height:5em;", placeholder:"Description du projet" %>
                  Ville
                  <%= f.collection_select :city_id, City.order(:name), :id,:name, {}, {class: "custom-select mr-sm-2"}%>
                  <br><br>
                  
      Photos

      <div class="input-group">
        <span class="input-group-btn">
          <span class="btn btn-success btn-success btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Parcourir</span>
          <%= f.file_field :picture1, :accept => 'jpg/png', onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
        </span>
        <span class="form-control"></span>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-btn">
          <span class="btn btn-small btn-success btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Parcourir</span>
          <%= f.file_field :picture2, :accept => 'jpg/png', onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
        </span>
        <span class="form-control"></span>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-btn">
          <span class="btn btn-small btn-success btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Parcourir</span>
          <%= f.file_field :picture3, :accept => 'jpg/png', onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
        </span>
        <span class="form-control"></span>
      </div>
      <br><br>
      <%= f.submit 'Envoyer', class:"btn btn-success" %>
                  <% end %>
                  <% else %>
                  <% controller.redirect_to root_path %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>                 
      </div>
    </div>
    </div>
  </div>
</section>

app/views/votes/_button.html.erb
<% if user_signed_in? %>

<% if current_user.vote?(@event) %>
<div class="btn" style="width: 100%; display: inline-block;">
  <%= button_to "ANNULER MON VOTE", unvote_path(event_id: @event.id), remote: true, method: :delete, class:"btn btn-black"%>
</div>
<% else %>
<div class="btn" style="width: 100%; display: inline-block;">
  <%= button_to "VOTER", vote_path(event_id: @event.id), remote: true, class:"btn btn-primary"%>
</div>
<% end %>



<% else %> 

Vous devez vous connecter pour voter.


<% end %>
<div class="all">

	<br>
    <div class="progress progress-xxs center" style="width: 100%; max-width: 100%; height: 3.5em; display: inline-block; text-align: center; position: inherit">
   		<div class="progress-bar" style="width: <%= (((@event.votes.count)*100)/User.count) %>%; max-width: 100%; height: 3.5em;background-color: #99D17B"></div>
    </div>

    <div class="percentage" style="width: 100%; display: inline-block; text-align: center"><b> <%= @event.votes.count %> </b> <br> membres ont été convaincus par ce projet.  </div>
    
</div>

</div>

app/views/votes/_count.html.erb
<%= @event.votes.count %>

app/views/votes/unvote.js.erb
$('div#<%= dom_id(@event) %>').html('<%= j render partial: "button", locals: {post: @event} %>');

app/views/votes/vote.js.erb
$('div#<%= dom_id(@event) %>').html('<%= j render partial: "button", locals: {post: @event} %>');