config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match 'vote', to: 'votes#vote', via: :post
  match 'unvote', to: 'votes#unvote', via: :delete

  resources :events
  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    validates :name, uniqueness: true
    has_one :place
end

app/models/event.rb
class Event < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :place_id, presence: true

    belongs_to :place
    has_many :votes, dependent: :destroy
    has_many :users, through: :votes
    has_one_attached :picture1
    has_one_attached :picture2
    has_one_attached :picture3
end

app/models/place.rb
class Place < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :events
    belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

# after_create :send_welcome_mail

  has_many :votes, dependent: :destroy
  has_many :events, through: :votes

  def send_welcome_mail
	#  UserMailer.welcome_email(self).deliver_now!
  end

    # creates a new vote row with event_id and user_id
  def vote!(event)
    self.votes.create!(event_id: event.id)
  end

  # destroys a vote with matching event_id and user_id
  def unvote!(event)
    vote = self.votes.find_by_event_id(event.id)
    vote.destroy!
  end

  # returns true of false if a event is voted by user
  def vote?(event)
    self.votes.find_by_event_id(event.id)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :event, counter_cache: true

    validates :user_id, uniqueness: { scope: :event_id }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
@cities = City.all 
protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

		devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
	end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.friendly.find(params[:id])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.where(:active => true)
  end

  def show
    @event = Event.friendly.find(params[:id])
    @city_of_event = City.find(Place.find(Event.friendly.find(params[:id]).place_id).id)
    @place_of_event = Place.find(Event.friendly.find(params[:id]).place_id)
  end

  def events_params
    params.require(:events).permit(:picture1)
    params.require(:events).permit(:picture2)
    params.require(:events).permit(:picture3)
  end

  def create

  	@event_new = Event.new(
      name: params[:new][:name], 
      description: params[:new][:description], 
      place_id: Place.find_by(city_id: params[:new][:city_id]).id, 
      picture1: params[:new][:picture1], 
      picture2: params[:new][:picture2], 
      picture3: params[:new][:picture3]
    )
    
    if @event_new.save && params[:new][:picture1].present?
      flash[:notice] = "Projet créé avec succès !"
      redirect_to root_path
    else 
      flash[:notice] = "Merci de réessayer"
  		redirect_to new_event_path
  	end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @cities = City.order(Arel.sql("RANDOM()")).limit(3)
    @places = Place.all
    @events = Event.all
  end

end

app/controllers/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

    respond_to :js

    def vote
      @user = current_user
      @event = Event.find(params[:event_id])
      @user.vote!(@event)
    end
    
    def unvote
      @user = current_user
      @vote = @user.votes.find_by_event_id(params[:event_id])
      @event = Event.find(params[:event_id])
      @vote.destroy!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
			<footer id="footer">
				<div class="container">

					<div class="row">
						
						<div class="col-md-3">
							<!-- Footer Logo -->
<!-- 							<img class="footer-logo" src="assets/images/_smarty/logo1.png" height="60em" alt="" />
 -->	<%= image_tag('logo1.png', height: "60em") %>
							<!-- Small Description -->
							<p>Nous réintroduisons la vie dans les espaces abandonnés.</p>

							<!-- Contact Address -->
							<address>
								<ul class="list-unstyled">
									<li class="footer-sprite address">
										Sehra Corp.<br>
										 Ras la Tasse <br>
										 3 Rue du Puits Vert,<br>
										 31000 Toulouse<br>
									</li>
									<li class="footer-sprite phone">
										Contact: 1-800-565-2390
									</li>
									<li class="footer-sprite email">
										<a href="mailto:sehra.service@gmail.com">sehra.service@gmail.com</a>
									</li>
								</ul>
							</address>
							<!-- /Contact Address -->

						</div>

						<div class="col-md-3">

							<!-- Latest Blog Post -->
							<h4 class="letter-spacing-1">DERNIERES NEWS</h4>
							<ul class="footer-posts list-unstyled">
								<li>
									<a href="https://www.lemonde.fr/smart-cities/article/2018/12/04/le-grand-paris-redonne-vie-aux-cathedrales-industrielles-desertees_5392419_4811534.html">Le Grand Paris redonne vie aux cathédrales industrielles désertées</a>
									<small>04 Décembre 2018</small>
								</li>
                                <li>
									<a href="https://www.letelegramme.fr/france/seine-saint-denis-les-friches-industrielles-des-laboratoires-culturels-et-festifs-ephemeres-26-08-2018-12061059.php">Les friches industrielles, des laboratoires culturels et festifs éphémères</a>
									<small>26 Août 2018</small>
								</li>
								<li>
									<a href="https://www.20minutes.fr/toulouse/2243539-20180325-toulouse-mois-friche-urbaine-deviendra-veritable-ephemere-cinema">Toulouse: Dans un mois, cette friche urbaine deviendra un véritable (mais éphémère) cinéma</a>
									<small>25 Mars 2018</small>
								</li>
							</ul>
							<!-- /Latest Blog Post -->

						</div>

						<div class="col-md-2">

							<!-- Links -->
							<h4 class="letter-spacing-1">EXPLORE SEHRA</h4>
							<ul class="footer-links list-unstyled">
								<li><%=link_to "Home", root_path%></li>
								<li><%=link_to "Les villes", cities_path%></li>
								<li><%=link_to "Les projets", events_path%></li>
							</ul>
							<!-- /Links -->

						</div>

						<div class="col-md-4">

							<!-- Newsletter Form -->
							<h4 class="letter-spacing-1">KEEP IN TOUCH</h4>
							<p>Inscrivez-vous pour avoir l'avant-première sur tous <br />les projets !</p>

							<form class="validate" action="/" method="get" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Entrez votre Email">
									<span class="input-group-btn">
										<button class="btn btn-success" type="submit">S'inscrire</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->

							<!-- Social Icons -->
							<div class="mt-20">
								<a href="https://www.facebook.com/" class="social-icon social-icon-border social-facebook float-left" data-toggle="tooltip" data-placement="top" title="Facebook">

									<i class="icon-facebook"></i>
									<i class="icon-facebook"></i>
								</a>

								<a href="https://twitter.com/?lang=fr" class="social-icon social-icon-border social-twitter float-left" data-toggle="tooltip" data-placement="top" title="Twitter">
									<i class="icon-twitter"></i>
									<i class="icon-twitter"></i>
								</a>

								<a href="https://www.google.fr/" class="social-icon social-icon-border social-gplus float-left" data-toggle="tooltip" data-placement="top" title="Google plus">
									<i class="icon-gplus"></i>
									<i class="icon-gplus"></i>
								</a>

								<a href="https://fr.linkedin.com/" class="social-icon social-icon-border social-linkedin float-left" data-toggle="tooltip" data-placement="top" title="Linkedin">
									<i class="icon-linkedin"></i>
									<i class="icon-linkedin"></i>
								</a>

								<a href="https://fr.wikipedia.org/wiki/RSS" class="social-icon social-icon-border social-rss float-left" data-toggle="tooltip" data-placement="top" title="Rss">
									<i class="icon-rss"></i>
									<i class="icon-rss"></i>
								</a>
					
							</div>
							<!-- /Social Icons -->

						</div>

					</div>

				</div>

				<div class="copyright">
					<div class="container">
						&copy; All Rights Reserved, SEHRA. LTD
					</div>
				</div>
			</footer>
			<!-- /FOOTER -->

app/views/layouts/_navbar.html.erb
			
			<% if current_page?(root_url) %>
            <div id="header" class="navbar-toggleable-md sticky transparent clearfix">
			<% else %>
			<div id="header" class="navbar-toggleable-md sticky clearfix">
			<% end %>
                <!-- TOP NAV -->
                <header id="topNav">
					<div class="container">

					<!-- Mobile Menu Button -->
					<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

					<!-- BUTTONS -->
					<ul class="float-right nav nav-pills nav-second-main">
						</ul>
						<!-- /BUTTONS -->

						<!-- Logo -->
					<% if current_page?(root_url) %>
						<a class="logo float-left" href="/">
							<%= image_tag("logo4.png") %>
							<%= image_tag("logo2.png") %>

						</a>
						<a class="logo float-left" href="/">
							<%= image_tag("logo1.png") %>
							<%= image_tag("logo3.png") %>
						</a>
					<% else %>
						<a class="logo float-left" href="/">
							<%= image_tag("logo2.png") %>

						</a>
						<a class="logo float-left" href="/">
							<%= image_tag("logo3.png") %>
						</a>

					<% end %>

						<!-- Top Nav -->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">
								<ul id="topMain" class="nav nav-pills nav-main">
									<li><!-- HOME -->
										<%= link_to "HOME", root_path %>
									</li>
									<li class="dropdown"><!-- PAGES -->
										<a class="dropdown-toggle" href="#">
											VILLES
										</a>
										<ul class="dropdown-menu">
											<li> <%= link_to "Toutes les Villes", cities_path %>
											<% City.all.each do |city| %>
											<li>
												<%= link_to city_path(id: city) do %>
        										<%= city.name %>
        										<% end %>
											</li>
											<% end %>
										</ul>
										
									</li>
									<li class="dropdown"><!-- FEATURES -->
										<%= link_to "PROJETS", events_path, class: "dropdown-toggle noicon" %>				
									</li>
									<li class="dropdown">
										<% if user_signed_in? && current_user.admin?  %>
											<%= link_to "ADMIN DASHBOARD", rails_admin_path, class: "dropdown-toggle noicon" %>
										<%elsif user_signed_in? %>
											<%= link_to "PROPOSER UN PROJET", new_event_path, class: "dropdown-toggle noicon"%>
										<%else%>
											<%= link_to "PROPOSER UN PROJET", new_user_session_path, class: "dropdown-toggle noicon"%>
										<%end%>
									</li>
								<% if user_signed_in?  %>
									<li class="dropdown nav-animate-fadeIn nav-hover-animate hover-animate-bounceIn"><!-- THEMATIC -->
										<a class="dropdown-toggle" href="#">
											<span class="badge badge-danger float-right fs-11" style="background-color: #1ABC9C">Connecté</span>
											<b>COMPTE</b>
										</a>
                                        <ul class="dropdown-menu">
                                        	<li class="dropdown">
                                        		<h4>Connecté en tant que: <%= current_user.first_name.capitalize  %></h4>
                                        	</li>
											<li class="dropdown">
												<%= link_to "Modifier mon compte", edit_user_registration_path %>
											</li>
                                            <li class="dropdown">
                                            	<%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
											</li>
                                            <li class="dropdown">
												
											</li>
										</ul>
									</li>
								<% else %>
									<li class="dropdown nav-animate-fadeIn nav-hover-animate hover-animate-bounceIn"><!-- THEMATIC -->
										<a class="dropdown-toggle" href="#">
											<b>COMPTE</b>
										</a>
                                        <ul class="dropdown-menu">
											<li class="dropdown">
												<%= link_to "Se connecter", new_user_session_path, class: "dropdown-toggle" %>
											</li>
                                            <li class="dropdown">
                                            	<%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-toggle" %>
											</li>
                                            <li class="dropdown">
												
											</li>
										</ul>
									</li>
								<%end%>

								</ul>

							</nav>
						</div>

					</div>
					
				</header>

			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SEHRA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag("logo2.png") %>
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
    
    <link rel="apple-touch-icon" sizes="57x57" href="assets/images/_smarty/icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="assets/images/_smarty/icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="assets/images/_smarty/icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/images/_smarty/icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="assets/images/_smarty/icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="assets/images/_smarty/icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="assets/images/_smarty/icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="assets/images/_smarty/icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/_smarty/icon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="assets/images/_smarty/icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/images/_smarty/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/images/_smarty/icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/_smarty/icon/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="assets/images/_smarty/icon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

       <%= render "layouts/navbar" %>

       <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131078903-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-131078903-1');
    </script>
       
  </head>

  <body>

    <%= yield %> 

  <!-- SCROLL TO TOP -->
      <a id="toTop"></a>

  <!-- JAVASCRIPT FILES -->
  <script>var plugin_path = '/assets/plugins/';</script>

  <!-- SCRIPTS -->


  </body>

  <footer>

  <%= render "layouts/footer" %>

  </footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>